### ISSUE TITLE
Fix file analysis code

### ISSUE THREAD

**Issue by tphakala** [tphakala/birdnet-go#108]
File analysis code is currently broken and file analysis is removed from command line options. Code should fixed and cli options restored.

**Comment by isZumpo** [comment]
I have a pull request in the works where I am planning on commenting out the cmd and file command files. Should I still go ahead and include that in the pull request or do we have a fix coming for it soon?

**Comment by tphakala** [comment]
I haven't started work on this yet, so any pull requests are appreciated.

**Comment by tphakala** [comment]
I just pushed PR #109 which restores file and directory analysis commands and functionality, golanci-lint is no longer complaining about these.
