### ISSUE TITLE
Help with birdweather token

### ISSUE THREAD

**Issue by duan78** [tphakala/birdnet-go#125]
Hi, it may be a dumb question but : where can I find birdweather access token ?

**Comment by tphakala** [comment]
Hi, it is a good question actually as I now realise that I have not documented this. You need to request a personal token from BirdWeather.com by email.

Send email to [birdnetpi@birdweather.com](mailto:birdnetpi@birdweather.com) with following content

> Hi, Tim, and thank you so much for BirdWeather.com!
> 
> Below is the information I would like to use to request a BirdWeather ID to use with BirdNET-Go
> 
> Latitude=00.000
> Longitude=00.00
> City= [ ]
> State= [ ]
> Country= [ ]
> 
> 
> Thank you so much!
> [ Your Name ]
> 
> Disclaimer: By requesting this BirdWeather ID, I acknowledge that my location and recording data will be made public. 

You will receive a token as a reply, I believe that token requests are handled manually so response may take a day or two.
