### ISSUE TITLE
"Failed to remove clips" forever

### ISSUE THREAD

**Issue by farski** [tphakala/birdnet-go#149]
It seems like when the process to prune clips is unable to (because the file was removed some other way), it doesn't do anything to prevent trying in the future. If it finds that a clip file has already deleted, it probably should update the DB/etc to reflect that, just as it would do normally.

**Comment by isZumpo** [comment]
Should be easy to add some sort of if condition if the file no longer exist, which would remove it from the DB. Suppose it should fail for other issues, for instance wrong file permissions when trying to delete
