### ISSUE TITLE
Loading some routes directly causes layout/style issues

### ISSUE THREAD

**Issue by farski** [tphakala/birdnet-go#158]
For example loading `http://birdnet.local:8080/species-detections?species=Northern+Parula&date=2024-05-10` for me yields
<img width="1440" alt="Screenshot 2024-05-10 at 07 45 44" src="https://github.com/tphakala/birdnet-go/assets/3483/15023572-c567-443e-9a7e-1ff78721121d">

**Comment by tphakala** [comment]
It is a known issue stemming from way HTMX works, fix is not very high on my priority list.

**Comment by tphakala** [comment]
This issue was kindly fixed by @petterip
