### ISSUE TITLE
Pulseaudio 100% CPU

### ISSUE THREAD

**Issue by Shellfishgene** [tphakala/birdnet-go#173]
Hi!
I'm currently running birdnet-go on a Debian VM under Proxmox. Nothing apart from birdnet-go is running or installed. After a week or so the CPU goes to 100% usage and the VM barely responds anymore. The culprit seems to be pulseaudio, alternating /bin/pulseaudio and /bin/speech-dispatcher use all available CPU. Birdnet-go shows an error 'ring buffer full'. (And stuff about slow database, which is to be expected I guess.)
Is this a Birdnet issue or something with Pulseaudio/Debian?

**Comment by tphakala** [comment]
Difficult to say without more details, however 'ring buffer full' would indicate that something failed within BirdNET-Go.

I just released a new version, can you please update to that and use ALSA source instead of PulseAudio source? ALSA is recommeded audio source for time being, you can just uninstall pulseaudio unless you are using it for anything else.

**Comment by Shellfishgene** [comment]
Thanks, will try the new version.

**Comment by Shellfishgene** [comment]
I removed PulseAudio now, and updated to the current release 0.5.5, and run realtime with -j 1, but the CPU goes to 100% right away with only birdnet-go processes using any. It's a Intel Celeron G4900, one CPU core from Proxmox in a Debian VM. While that's not the greatest CPU it should suffice no?

**Comment by isZumpo** [comment]
Maybe you end up with lots of expensive context switching using a single cpu core? Since birdnet has to share cpu time with all other os activities. Even more since it is all running inside a vm. Can you try increasing the cpu core count to two as an experiment?

**Comment by Shellfishgene** [comment]
I did that now, after I restart the VM the problem always goes away and only returns after a few days or so. So for now it's back at ~8% CPU. We'll see how it goes.

**Comment by isZumpo** [comment]
Ok let see what happens over the next few days. Here is a screenshot of cpu usage for my birdnet container over a few days. It should be quite stable:

![Screenshot_20240726-160018.png](https://github.com/user-attachments/assets/f3e3e77f-3abc-4646-be3d-d62052b792e7)

**Comment by nicholasmparker** [comment]
FWIW im getting a ton of "ringbuffer is full" in the logs.  latest version via docker

**Comment by tphakala** [comment]
@nicholasmparker can you please provide

- Logs containing "ringbuffer is full" errors, they also contain debug output for this specific issue
- config.yaml, remove any sensitive settings like usernames, passwords, birdweather token, etc
- Detailed description of hardware and OS you are running BirdNET-Go on

Thank you

**Comment by tphakala** [comment]
@nicholasmparker can you please test with latest docker image? I have increased ring buffer size and added some additional logging in case error happens. Problem is that I am unable to reproduce this issue myself.

**Comment by nicholasmparker** [comment]
Running it now.  I will let you know!

**Comment by tphakala** [comment]
Closing this issue for now. If any ring buffer-related issues still occur, I encourage you to open a new issue
