### ISSUE TITLE
Direct links do not load CSS/some UI

### ISSUE THREAD

**Issue by PovilasID** [tphakala/birdnet-go#183]
Hey,

If you go url directly some elements like header and footer or sidebar  are not loaded, so you get no CSS.
What I mean by direct link is http://192.168.x.x:8080/species-detections?species=Eurasian+Blackcap&date=2024-05-31

**Comment by tphakala** [comment]
This is a known issue caused by way HTMX works, I guess this can be fixed but it is not very high on my task list at the moment.

**Comment by tphakala** [comment]
Duplicate https://github.com/tphakala/birdnet-go/issues/158
