### ISSUE TITLE
How to configure MQTT Client Id? 

### ISSUE THREAD

**Issue by simplemice** [tphakala/birdnet-go#222]
Hi, to connect several birdnets to one mqtt you need to change each client_id, I have not found this option in the config.

**Comment by tphakala** [comment]
Likely a missing feature at the moment, should be easy to implement though I guess. Will fix soon.

**Comment by tphakala** [comment]
https://github.com/tphakala/birdnet-go/pull/235 now implements a change which assigns BirdNET-Go node name as MQTT client_id, can you please test it if it works for you? Change is live in dev container image

**Comment by simplemice** [comment]
Hi, thanks for the work, everything works well, haven't detected any issues

`Connected to MQTT broker: tcp://localhost:1883`
