### ISSUE TITLE
Import observations from BirdNET-Pi

### ISSUE THREAD

**Issue by farski** [tphakala/birdnet-go#33]
This may already exist, but I couldn't find a mention. It'd be great to be able to bring over an export of observations from a BirdNET-Pi database

**Comment by tphakala** [comment]
There is not yet, but I have been thinking of making a tool for that. I'll see if I can make one over this weekend.

**Comment by tphakala** [comment]
I built conversion tool today, it is available at https://github.com/tphakala/birdnet-pi2go
