### ISSUE TITLE
Fix WAV encoding of BirdWeather uploads

### ISSUE THREAD

**Issue by tphakala** [tphakala/birdnet-go#68]
WAV files uploaded to BirdWeather are incorrectly encoded resulting non-working audio clip uploads

**Comment by MueJosh** [comment]
It even crashes the whole system, I had to do a fresh install since I had no backup of config.yaml 

If any errors are needed let me know

**Comment by tphakala** [comment]
Only issue with Birdweather uploads is that uploaded wav files are silent, there is no way that problem covered by this issue would cause loss of any files such as birdnet-go config file.

Please file a new issue with as much details as you can provide.

**Comment by tphakala** [comment]
PCM to WAV encoding fixed with 79ae3f4
