### ISSUE TITLE
Add Greek birdnames

### ISSUE THREAD

**Issue by hoover67** [tphakala/birdnet-go#72]
First of all: Great work & thanks for sharing your efforts! 

How can I add modern greek species names to the localizations already present? 

Thanks,

Uwe

**Comment by tphakala** [comment]
Hi, could you please attach labels file to this discussion for example and I will add it to codebase

**Comment by hoover67** [comment]
Sure, which format would be ok for you? I would guess latin / scientific -> greek or similar? 

Cheers, Uwe

**Comment by hoover67** [comment]
Here's a rudimentary labels_gr.txt file, however it only contains 540 entries and I am unsure how to add the third tag which I would guess some sort of abbreviation that's used internally by birdnet_go? 

Would the program revert / default to english or latin names if a localized version of the name is not found? 
[labels_gr.txt](https://github.com/tphakala/birdnet-go/files/14695927/labels_gr.txt)


Thanks, Uwe

**Comment by tphakala** [comment]
Thanks, line count and placement must match exactly this file
https://github.com/kahst/BirdNET-Analyzer/blob/main/labels/V2.4/BirdNET_GLOBAL_6K_V2.4_Labels_en_uk.txt

BirdNET model returns a line number for each match and if line content does not match with expected species results are wrong. So essentially translation should replace species in that list with localised entry and rest should be left as is.

**Comment by tphakala** [comment]
I wrote a script which built full labels file with your translations, I will include your translations into codebase soon.
[Uploading labels_gr_full.txt…]()

**Comment by tphakala** [comment]
I wrote a script which combines your provided labes_gr.txt with labels_en.txt to produce full labels file, this contains scientific name, common name (with translations) and 6 letter code. I will add this in codebase soon.

**Comment by hoover67** [comment]
Great news Tomi, I was just going to do that... thanks for taking care of it! 

All the best, 
uwe

**Comment by tphakala** [comment]
merged with b35b84df35f4b38ca6e025ad2a79d0b4bd2431d2
